PizzaShop_proj/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib import admin
from django.views.generic.base import RedirectView
from pizzashop_app.views import PizzaListView, LoginView, LogoutView, RegisterView, PizzaDetailView, BinView, \
    PizzaOrderView,BinCheckoutView, BinChangeQuantityView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include('api.urls') ),
    url(r'^accounts/profile/$',  RedirectView.as_view(url='/', permanent=False), name='index'),
    url(r'^$', PizzaListView.as_view(), name='pizza_list'),
    url(r'^login/$', LoginView.as_view()),
    url(r'^logout/$', LogoutView.as_view()),
    url(r'^register/$', RegisterView.as_view()),
    url(r'^(?P<pk>\d+)/$', view=PizzaDetailView.as_view(), name='pizza_details'),
    url(r'^bin/$', BinView.as_view()),
    url(r'^bin/checkout/$', BinCheckoutView.as_view()),
    url(r'^bin/change_quantity/$', BinChangeQuantityView.as_view()),
    url(r'^pizza/(?P<pk>\d+)/order/$', view=PizzaOrderView.as_view(), name='pizza_order'),
]

if settings.DEBUG:
    if settings.MEDIA_ROOT:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

api/urls.py
from django.conf.urls import include
from django.conf.urls import url
from rest_framework.routers import DefaultRouter
from .views import PizzaViewSet, PizzaRecipecViewSet, IngredientViewSet, OrderViewSet, OrderItemPizzaViewSet, DrinkViewSet, \
    DrinkViewSet, OrderItemDrinkViewSet

router = DefaultRouter()
router.register(r'pizzas', PizzaViewSet)
router.register(r'recipes', PizzaRecipecViewSet)
router.register(r'ingredients', IngredientViewSet)
router.register(r'orders', OrderViewSet)
router.register(r'orderitempizzas',OrderItemPizzaViewSet)
router.register(r'drinks', DrinkViewSet)
router.register(r'orderitemdrinks', OrderItemDrinkViewSet)


urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'api-auth/', include('rest_framework.urls',
                               namespace='rest_framework')),
]

pizzashop_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse


class Ingredients(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class PizzaRecipe(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField()
    description = models.TextField(blank=True)
    ingredients = models.ManyToManyField(Ingredients)

    def __str__(self):
        return self.name


class Pizza(models.Model):
    recipe = models.ForeignKey(PizzaRecipe)
    weight = models.PositiveIntegerField()
    diameter = models.PositiveIntegerField()
    price = models.FloatField()

    def __str__(self):
        return "{} {}".format(self.recipe.name, self.diameter, self.price)

    def get_absolute_url(self):
        return reverse('pizza_details', kwargs={'pk': self.pk})


class Drink(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField()
    price = models.FloatField()
    in_stock = models.PositiveIntegerField()
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name


class Order(models.Model):
    client = models.ForeignKey(User)
    date = models.DateTimeField(auto_now_add=True)
    pizzas = models.ManyToManyField(Pizza, through='OrderItemPizza')
    drinks = models.ManyToManyField(Drink, through='OrderItemDrink')

    CLOSED = 'closed'
    ACTIVE = 'active'
    STATUS_CHOICES = ((CLOSED, 'closed'),(ACTIVE, 'active'))
    status = models.CharField(max_length=100, choices=STATUS_CHOICES)

    def __str__(self):
        return "Order {}".format(self.pk)


class OrderItemPizza(models.Model):
    order = models.ForeignKey(Order, related_name='order_pizzas')
    pizza = models.ForeignKey(Pizza)
    quantity = models.PositiveIntegerField()

    def _get_total(self):
        return self.pizza.price * self.quantity
    total_cost = property(_get_total)


class OrderItemDrink(models.Model):
    order = models.ForeignKey(Order, related_name='order_drinks')
    drink = models.ForeignKey(Drink)
    quantity = models.PositiveIntegerField()

    def _get_total(self):
        return self.product.price * self.quantity
    total_cost = property(_get_total)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <script src="{% static 'js/script.js' %}"></script>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>{% block title %}{% endblock %}</title>
     {% block head %}
    <nav class="navbar navbar-default header">
        <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <a class="navbar-brand bg-info" href="/">Pizza!</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                {% if not user.is_authenticated %}
                <li><a href="/login/"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                <li><a href="/register/"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                {% else %}
                <li><a href="/bin/"><span class="glyphicon glyphicon-home"></span>Bin</a></li>
                <li><a href="/logout/"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
                {% endif %}
            </ul>
            <div class="search"></div>
        </div>
    </nav>
    {% endblock %}

</head>
<body>
<div class="container">
    {% block main %} {% endblock %}
</div>
<br>
</body>
</html>

templates/bin.html
{% extends 'base.html' %}

{%block main%}
{% if order_list %}
    Order details:
    {% for order_item in order_list %}
        {{order_item.pizza.recipe}} |
<form action="/bin/change_quantity/" method="POST" class="form-bin">
    {% csrf_token %}
    <input type="hidden" name="pizza_id" value="{{order_item.pizza.pk}}">
    <input type="number" name="quantity" max="10" min="1" value="{{order_item.quantity}}" style="width:33px">
    <button type="submit">Change</button>
</form>
<br><br>
    {% endfor %}
<br>
<p id="totalcost">Totalcost = {{total}}</p>
<form action="/bin/checkout/" method="POST">
    {% csrf_token %}
    <button type="submit">Checkout</button>
</form>
{% else %}
At this moment you have no active order
{% endif %}

{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block main %}

<form action="/login/" method="POST" class="login-form">
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" class="btn btn-primary" value="Войти"/>
</form>
{% endblock %}

templates/pizza_details.html
{% extends 'base.html' %}
{% block main %}
Pizza details:<br>

{{pizza.recipe}}
<img src="{{ pizza.image }}" class="img-responsive img-thumbnail"><br>
<img src="{{ pizza.recipe.image.url }}" style="width:500px; height:500px;">


{% endblock %}

templates/pizza_list.html
{% extends 'base.html' %}

{% block main %}
{% for pizza in pizza_list %}
            <nav class="navbar navbar-default">
                <div class="form-group">
                    <form action="pizza{{ pizza.get_absolute_url }}order/" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="pizza_id" value="{{pizza.id}}">
                        <p><input type="number" name="quantity" max="10" min="1" value="1" style="width:33px"></p>
                        <button type="submit">Order</button>
                    </form>
                    <!--<a href="pizza{{ pizza.get_absolute_url }}order/" class="btn btn-default btn-sm edit_button">-->
                        <!--Order</a>-->
                    <a href="{{pizza.get_absolute_url}}" class="product_name">{{ pizza.recipe.name }} Price {{pizza.price}} </a>
                </div>
            </nav>
            {% endfor %}
{% endblock %}

templates/pizza_order.html
{%extends 'base.html'%}
{%block main%}

{%endblock%}

templates/register.html
{%extends 'base.html'%}
{% block main %}
<form action="/register/" method="POST" class="registr-form">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" class="btn btn-primary btn-registr" value="Зарегистрироваться"/>
</form>
<br>
{% endblock %}